### ISSUE TITLE
Android 9 crash!

### ISSUE THREAD

**Issue by a6051529** [zgkxzx/Modbus4Android#18]
2020-04-02 23:13:33.705 18308-18308/com.example.lainaApp E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/logging/LogFactory;
        at com.zgkxzx.modbus4And.ip.tcp.TcpMaster.<init>(TcpMaster.java:57)
        at com.zgkxzx.modbus4And.ModbusFactory.createTcpMaster(ModbusFactory.java:69)
        at com.zgkxzx.modbus4And.requset.ModbusReq.init(ModbusReq.java:92)
        at com.example.lainaApp.utils.ModbusManager.initModbusReq(ModbusManager.java:65)
        at com.example.lainaApp.MainActivity$1.onMethodCall(MainActivity.java:109)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.LogFactory" on path: DexPathList[[zip file "/data/app/com.example.lainaApp-JLt9MxV_FKoPsCLXySNd3A==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.lainaApp-JLt9MxV_FKoPsCLXySNd3A==/lib/arm64, /data/app/com.example.lainaApp-JLt9MxV_FKoPsCLXySNd3A==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.zgkxzx.modbus4And.ip.tcp.TcpMaster.<init>(TcpMaster.java:57) 
        at com.zgkxzx.modbus4And.ModbusFactory.createTcpMaster(ModbusFactory.java:69) 
        at com.zgkxzx.modbus4And.requset.ModbusReq.init(ModbusReq.java:92) 
        at com.example.lainaApp.utils.ModbusManager.initModbusReq(ModbusManager.java:65) 
        at com.example.lainaApp.MainActivity$1.onMethodCall(MainActivity.java:109) 
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231) 
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93) 
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:326) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
2020-04-02 23:13:33.705 18308-18308/com.example.lainaApp A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
    
    
    --------- beginning of crash
2020-04-02 23:13:33.705 18308-18308/com.example.lainaApp A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18308 (xample.lainaApp), pid 18308 (xample.lainaApp)

**Comment by aravindor** [comment]
facing similar issue .. Did u find any solution ?

**Comment by spss20** [comment]
Add this line in Android manifest under application tag.
`<uses-library android:name ="org.apache.http.legacy" android:required ="false"/>`
